logfile:
  service:
    url: "localhost:10210/logfiles"

hadoopprj:
  rabbitmq:
    exchange:   hadoop-prj.exchange
  hdfs:
    tokem: R7zZQkdtYS0AwKQ7Zrdd


spring:
  datasource:
    url: jdbc:postgresql://home.yakimovvn.ru:5432/hadoopprj?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  flyway:
    locations: classpath:/db/migration
  rabbitmq:
    host: home.yakimovvn.ru
    port: 5672
    username: test
    password: test

